// server.js
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const bodyParser = require('body-parser');

const app = express();
const port = process.env.PORT || 5000;
app.use(cors());
app.use(bodyParser.json());

// MongoDB connection
mongoose.connect('mongodb://127.0.0.1:27017/mern_dashboard');


const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', () => {
  console.log('Connected to MongoDB');
});

// Data schema
const dataSchema = new mongoose.Schema({
  intensity: Number,
  likelihood: Number,
  relevance: Number,
  year: Number,
  country: String,
  topics: [String],
  region: String,
  city: String,
  sector: String,
  pest: String,
  source: String,
  swot: String,
});

const Data = mongoose.model('Data', dataSchema);

// API endpoint to fetch data
app.get('/api/data', async (req, res) => {
  try {
    const data = await Data.find({});
    console.log("data required")
    res.json(data);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

const filterOptions = {
  countries: [
    '',
    'Algeria',
    'Angola',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Belize',
    'Brazil',
    'Burkina Faso',
    'Canada',
    'China',
    'Colombia',
    'Cyprus',
    'Denmark',
    'Egypt',
    'Estonia',
    'Ethiopia',
    'Gabon',
    'Germany',
    'Ghana',
    'Greece',
    'Hungary',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Lebanon',
    'Liberia',
    'Libya',
    'Malaysia',
    'Mali',
    'Mexico',
    'Morocco',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Poland',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Syria',
    'Turkey',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Venezuela'
  ],
  topics: [
    '',
    '3D',
    'Washington',
    'administration',
    'agriculture',
    'aquaculture',
    'artificial intelligence',
    'asylum',
    'automaker',
    'bank',
    'battery',
    'biofuel',
    'brexit',
    'building',
    'business',
    'capital',
    'car',
    'carbon',
    'change',
    'city',
    'climate',
    'climate change',
    'clothing',
    'coal',
    'communication',
    'consumer',
    'consumption',
    'crisis',
    'data',
    'debt',
    'demand',
    'economic',
    'economic growth',
    'economy',
    'election',
    'electricity',
    'emission',
    'energy',
    'export',
    'factory',
    'farm',
    'finance',
    'food',
    'fossil fuel',
    'fracking',
    'gamification',
    'gas',
    'gasoline',
    'gdp',
    'government',
    'greenhouse gas',
    'growth',
    'ice',
    'industry',
    'inflation',
    'information',
    'infrastructure',
    'interest rate',
    'investment',
    'market',
    'material',
    'money',
    'nuclear',
    'oil',
    'peak oil',
    'plastic',
    'policy',
    'politics',
    'pollution',
    'population',
    'power',
    'production',
    'resource',
    'revenue',
    'risk',
    'robot',
    'security',
    'shale gas',
    'shortage',
    'software',
    'storm',
    'strategy',
    'tax',
    'technology',
    'tension',
    'terrorism',
    'tourist',
    'trade',
    'transport',
    'transportation',
    'unemployment',
    'vehicle',
    'war',
    'water',
    'wealth',
    'work',
    'worker',
    'workforce'
  ],
  sectors: [
    '',                       'Aerospace & defence',
    'Automotive',             'Construction',
    'Energy',                 'Environment',
    'Financial services',     'Food & agriculture',
    'Government',             'Healthcare',
    'Information Technology', 'Manufacturing',
    'Media & entertainment',  'Retail',
    'Security',               'Support services',
    'Tourism & hospitality',  'Transport',
    'Water'
  ],
  regions: [
    '',                'Africa',
    'Asia',            'Central Africa',
    'Central America', 'Central Asia',
    'Eastern Africa',  'Eastern Asia',
    'Eastern Europe',  'Europe',
    'Northern Africa', 'Northern America',
    'Northern Europe', 'Oceania',
    'South America',   'South-Eastern Asia',
    'Southern Africa', 'Southern Asia',
    'Southern Europe', 'Western Africa',
    'Western Asia',    'Western Europe',
    'World',           'world'
  ],
  pest: [
    '',
    'Economic',
    'Environmental',
    'Healthcare',
    'Industries',
    'Lifestyles',
    'Organization',
    'Political',
    'Social',
    'Technological'
  ],
  sources: [
    "",
      "EY",
      "IFT",
      "Hospitality Trends",
      "GlobalMeatNews.com",
      "cargill",
      "globalr2p",
      "CAFrackFacts",
      "Environmental Leader",
      "FX Empire",
      "Newsweek",
      "Oxfam",
      "The Atlantic",
      "friday-thinking",
      "MENA-Forum",
      "Transport Evolved",
      "Innovations Report",
      "Rigzone",
      "Gizmodo Australia",
      "Interior Design",
      "cpzulia",
      "Cushman & Wakefield Blog",
      "Maplecroft",
      "Bearnobull",
      "inputsmonitor",
      "Gas 2",
      "idc-community",
      "satprnews",
      "Phys Org",
      "HBR",
      "UNESCO ",
      "CIO",
      "dailyquiddity",
      "Business Green",
      "Atlantic Council ",
      "EPS News",
      "Face2face Africa",
      "The Ticker Tape",
      "Oil and Gas Journal",
      "PwC",
      "marketrealist",
      "Wall Street Daily",
      "Resources for the Future",
      "Utility Dive",
      "IISS",
      "oilvoice",
      "The Next Web",
      "No 2 Nuclear Power",
      "Biofuels Digest",
      "Zero Hedge",
      "Guarini Center",
      "Global Money Trends",
      "The Conversation",
      "The Market Mogul",
      "AllAfrica",
      "South Sudan News Agency",
      "Justmeans",
      "Smart Grid Observer",
      "ECFR",
      "EE News",
      "Mast",
      "JD Supra",
      "The Mainichi",
      "International Business Times",
      "Activist Post",
      "Farms.com",
      "OklahomaMinerals.com",
      "Think Progress",
      "Climate News Network",
      "Wharton",
      "MAPI",
      "WSJ",
      "Worldly",
      "FoodQualityNews.com",
      "Transport Environment",
      "murc",
      "Future Earth",
      "MIT Sloan Management Review",
      "Azonano",
      "UNEP",
      "NWF",
      "Guardian Sustainable Business",
      "amundi",
      "Insurance Journal",
      "Jachin Capital",
      "Fitch",
      "Predictive Analytics Times",
      "The Engineer",
      "ISA",
      "U.S. Environmental Protection Agency",
      "Robothub",
      "Canadian Biomass",
      "Freedonia",
      "University of Chicago",
      "University Chronicle",
      "khorreports-palmoil",
      "westpandi",
      "BBC News Technology",
      "Government of Ireland",
      "GreenBiz",
      "Ocean Acidification",
      "agriworldsa",
      "Manufacturing Operations Technology Viewpoints",
      "Avi Melamed",
      "Bloomberg Business",
      "Virgin Atlantic",
      "aswm",
      "McKinsey & Company",
      "Inside Climate News",
      "UK Government",
      "EV Obsession",
      "IMF",
      "EPA",
      "Informed Choice Chartered Financial Planners in Cranleigh",
      "Europa",
      "maltawinds.com",
      "GE Reports",
      "Countries.com Global Content",
      "Time",
      "jeita",
      "Neon Nettle",
      "Newsletter",
      "Eurasia Group",
      "ReadWrite",
      "AHDB",
      "The Jakarta Post",
      "Gii Research",
      "SlideShare",
      "CCN: Financial Bitcoin & Cryptocurrency News",
      "VOA",
      "conferenceseries",
      "greenerearthnews",
      "European Central Bank",
      "Nanotechnology Innovation",
      "sustainablebrands.com",
      "platts",
      "OEM/Lube News",
      "Nexus Conference",
      "Drill or drop?",
      "ESPAS",
      "The Globe and Mail",
      "DOE EIA 2013 Energy Conference",
      "Handelsblatt Global Edition",
      "IER",
      "watercanada",
      "National Geographic Society (blogs)",
      "Thomson Reuters ",
      "Yahoo Finance",
      "biomassmagazine",
      "Pickens Plan",
      "Cii Radio",
      "njc-cnm",
      "Sputnik News",
      "EGYPS",
      "TRAC News",
      "PDQFX news",
      "unian",
      "The Independent",
      "Lawfare",
      "valburyresearch",
      "Russia Beyond The Headlines",
      "PR Newswire",
      "Euromoney",
      "CDC",
      "U.K. Ministry of Defense",
      "iMFdirect - The IMF Blog",
      "Politico",
      "environmentalpeacebuilding",
      "World Bank Group",
      "Technavio",
      "IEA.org",
      "FutureinFocus",
      "Imeche",
      "The Arab Gulf States Institute Washington",
      "Triple Pundit",
      "TheNews.NG",
      "Global Information Inc",
      "EIU",
      "Motor Magazine",
      "g7g20",
      "The American Prospect",
      "prsync",
      "3D Printing Progress",
      "IASTOPPERS",
      "News.com",
      "Australian Government",
      "Wells Fargo",
      "ebrd",
      "Reuters",
      "Society of Motor Manufacturers and Traders (SMMT)",
      "Shenandoah",
      "bankofengland",
      "Innovate UK",
      "betterenergy",
      "Hardin Tibbs",
      "Energy Tomorrow",
      "Energy.gov Website",
      "OPEC",
      "dailytexanonline",
      "LiveMint",
      "The Jamestown Foundation",
      "Critical Threats",
      "Guardian",
      "Cushman & Wakefield",
      "Brookings Institute",
      "knomad",
      "Planetizen",
      "iamericas",
      "Futureseek Link Digest",
      "Euler Hermes",
      "University of Latvia",
      "DW.COM",
      "CNBC ",
      "Futurity",
      "ID TECH INDEX",
      "ihsmarkit",
      "Business Standard",
      "europeanclimate",
      "AMERICAN COUNCIL ON SCIENCE AND HEALTH",
      "portfolioticker",
      "Finance Magnates",
      "controleng",
      "Tactical Investor",
      "www.narendramodi.in",
      "Renewable Energy World",
      "Yahoo Finance Canada",
      "worldenergy",
      "VITA Technologies",
      "Abq",
      "thespanisheconomy",
      "Convenience Store Decisions",
      "European Council",
      "Real Estate Professional",
      "Mind Commerce",
      "Climate Change News",
      "creamermedia",
      "African Arguments",
      "Wired UK",
      "Prospects for Development",
      "energy news cyprus",
      "Scientific American",
      "EIA",
      "CSIS",
      "Science Daily",
      "Middle East Eye",
      "Investopedia",
      "Embedded Computing Design",
      "Australian Government Department of Defence",
      "Le·gal In·sur·rec·tion",
      "Science News",
      "IEA",
      "Nation of Change",
      "Before It's News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News",
      "ETEnergyworld.com",
      "International Monetary Fund (IMF)",
      "World Energy News",
      "European Environment Agency",
      "bankofcanada",
      "IBEF",
      "clientadvisoryservices",
      "Future Market Insights",
      "Digitalist Magazine",
      "edie.net",
      "Seeking Alpha",
      "nextbigfuture",
      "Channel News Asia",
      "Koenig Investment Advisory",
      "Star Tribune",
      "Bloomberg New Energy Finance",
      "Innovaro",
      "djsresearch",
      "Slinking Toward Retirement",
      "Total",
      "AgWeb - The Home Page of Agriculture",
      "Drydock Magazine",
      "Vox",
      "Adam Curry",
      "nbk",
      "Fast Co-Exist",
      "4th Annual Congress and Expo on Biofuels and Bioenergy April 27-28 2017 Dubai UAE",
      "Khaleej Times",
      "Arangkada Philippines",
      "INSEAD Knowledge",
      "Middle East Online",
      "ogauthority",
      "Quartz",
      "polymerspaintcolourjournal",
      "Wikipedia",
      "Infracircle",
      "saltlakecityheadlines",
      "globalmoneytrends",
      "PriceWaterhouseCoopers",
      "Vanguard News",
      "TeleTrade",
      "veteranstoday",
      "uschamber",
      "the star online",
      "USDA",
      "Days Of Year",
      "economy",
      "The Nation",
      "MRC",
      "ethicalconsumer",
      "ecesr",
      "worldculturepictorial",
      "Future in Focus",
      "Citibank",
      "RiskMap 2017",
      "atradius",
      "biologicaldiversity",
      "globalizationpartners",
      "cloudfront",
      "Europe in My Region",
      "",
      "Huffington Post",
      "Wood McKenzie",
      "Future Timeline",
      "Zawya",
      "Planetsave ",
      "Elsevier",
      "globalfueleconomy",
      "Business Wire",
      "dpaq",
      "Nature",
      "Washington Post",
      "arabellaadvisors",
      "CleanTechnica",
      "Strategy & Formerly Booz & Company",
      "New Security Beat",
      "The Guardian",
      "Cars.co.za",
      "CNNMoney",
      "farms",
      "BorneoPost Online",
      "Peak Prosperity",
      "OMFIF",
      "ethicalmarkets",
      "TheCable",
      "World Health",
      "Blue and Green Tomorrow",
      "THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA",
      "IRENA",
      "IHS Engineering 360",
      "Fews Net",
      "newscientist",
      "Project Syndicate",
      "THISDAY LIVE",
      "Eco-Business.com",
      "LNG",
      "Foreign Policy",
      "MIT Technology Review",
      "Scania Group",
      "South World",
      "Industrial Control Security",
      "The Economist",
      "Business Insider",
      "Institutional Investor",
      "briandcolwell",
      "Aljazeera.com",
      "metalprices",
      "Common Dreams",
      "News",
      "Tech Times",
      "African Development Bank",
      "Verisk Maplecroft",
      "FAO",
      "South China Morning Post",
      "Cornell University",
      "Media Center ",
      "International Banker",
      "RUSI",
      "Yes Bank",
      "The Chirographer",
      "therobotreport",
      "Carbon Brief",
      "allianzglobalinvestors",
      "CAJ News Africa",
      "FashionNetwork.com",
      "NDTV",
      "Gartner",
      "CBO",
      "gasstrategies",
      "nbp",
      "McKinsey Quarterly",
      "IRENA newsroom",
      "Industry Week",
      "Engineering News",
      "Fox Business",
      "Sydney Morning Herald",
      "World Bank",
      "oilprice.com",
      "energyglobal",
      "NY Times",
      "Resilience",
      "Edge and Odds",
      "What's Next",
      "Global Money Trends Magazine",
      "savepassamaquoddybay",
      "Stanford News",
      "Freenewspos",
      "War on the Rocks",
      "SBWire",
      "theicct",
      "About Best Binary Options Strategy",
      "Physics World"
    ]
  ,
  swot: ['Strengths', 'Weaknesses', 'Opportunities', 'Threats']
};

app.get('/api/filter-options', (req, res) => {
  res.json(filterOptions);
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
